;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GAS.State.Moving",DevComment="이동중일 때 붙는 태그")
GameplayTagList=(Tag="GAS.Test.Ability.Blink.Cooldown",DevComment="테스트용")
GameplayTagList=(Tag="GAS.Test.Debuff.Curse",DevComment="테스트용 디버프")
GameplayTagList=(Tag="GAS.Test.SetByCaller",DevComment="테스트용")
GameplayTagList=(Tag="GAS.Test.Type.Undead",DevComment="테스트용")

